feat: pagination implementation
nevence/VacaYAY pull request #4
Opened 2024-05-28 08:46 UTC by nevence

implemented pagination using RequestParameters (PageNumber, PageSize) and DtoViewModel which contains MetaData (CurrentPage, TotalPages, PageSize,TotalCount, HasPrevious, HasNext) and IEnumerable<T> properties

2024-05-29 06:13 UTC, pdavitkovic requested changes

2024-05-29 06:13 UTC, pdavitkovic commented on VacaYAY/BusinessLogicLayer/ViewModel/DtoViewModel.cs
> +    public class DtoViewModel<T>
What the DtoViewModel mean?

2024-05-29 06:41 UTC, nevence commented on VacaYAY/BusinessLogicLayer/ViewModel/DtoViewModel.cs
> +    public class DtoViewModel<T>
It is like a generic Response class that consists of List with dtos (list contains paginated records), and also MetaData - it is a class that contains information about pagination, like current page, total pages, page size, total count, has previous and has next. I need these MetaData properties so i can create a pagiantion component in the View (frontend)

I decided not to create a PagedList that inherits from List. I wanted to make it simpler and create something like a response class with List containing paginated records - dtos, and also information about pagination - total pages, current page, page size....

2024-05-30 12:17 UTC, pdavitkovic approved these changes

2024-05-30 12:17 UTC, merged