feat: consuming a newly created Web API by registering Employees
nevence/VacaYAY pull request #5
Opened 2024-06-03 13:20 UTC by nevence

created a new Web API project that generates random employees using Bogus, created new classes in MVC to deserialize api response, and consuming the API by registering new employees using transaction

2024-06-03 13:22 UTC, nevence commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add API calls for all entities](https://trello.com/c/XdxVyunO/4-add-api-calls-for-all-entities)

2024-06-04 07:18 UTC, pdavitkovic requested changes

2024-06-04 07:18 UTC, pdavitkovic commented on VacaYAY/BusinessLogicLayer/Services/AuthService.cs
> +            using var transaction = await _repository.BeginTransactionAsync();
Why transaction?

2024-06-04 07:40 UTC, nevence commented on VacaYAY/BusinessLogicLayer/Services/AuthService.cs
> +            using var transaction = await _repository.BeginTransactionAsync();
to be secure that, if for example 5 employees are sucessfully registered, and 6th one fails, everything can be rolled back to the beginning point. since we are using createasync method (for registering employees) without dbcontext savechanges (method that acts like a transaction) i wasn't sure how this could be handled. do you think this approach isn't valid?

2024-06-04 07:57 UTC, pdavitkovic requested changes

2024-06-04 07:57 UTC, pdavitkovic commented on VacaYAY/BusinessLogicLayer/Services/AuthService.cs
> +                var response = await _httpClient.GetAsync(_api.BaseUrl + "/Employees");
Magic string again :)

2024-06-04 07:57 UTC, pdavitkovic commented on VacaYAY/BusinessLogicLayer/Services/AuthService.cs
> +            using var transaction = await _repository.BeginTransactionAsync();
Seems fine by me. Nice addition :)

2024-06-04 08:01 UTC, nevence commented on VacaYAY/BusinessLogicLayer/Services/AuthService.cs
> +                var response = await _httpClient.GetAsync(_api.BaseUrl + "/Employees");
i can't believe how i didn't notice that... i really tried to avoid magic strings by using options pattern (ioptions<apiconfig> for baseurl), and this "employee" hardcoding somehow totally went past me..

2024-06-04 12:46 UTC, pdavitkovic requested changes

2024-06-04 12:46 UTC, pdavitkovic commented on VacaYAY/BusinessLogicLayer/Services/AuthService.cs
> +                var response = await _httpClient.GetAsync(_api.BaseUrl + ApiRoutes.GetEmployees);
I have an idea here:

You can ditch the transaction here and use only one SaveChanges, but all porting logic is in try/catch blog.

2024-06-04 19:18 UTC, nevence commented on VacaYAY/BusinessLogicLayer/Services/AuthService.cs
> +                var response = await _httpClient.GetAsync(_api.BaseUrl + ApiRoutes.GetEmployees);
but how would that solve the problem with incomplete employee migration (registration). i also checked microsoft's documentation, createasync method creates a user and stores it in the database - "Creates the specified user in the backing store with given password, as an asynchronous operation."

in my opinion, transaction is the best solution. calling explicitly savechanges method and using try catch block wouldn't do anyting, because a successful createasync method creates a user and saves it in the database. 

please correct me if i'm wrong because i didn't quite understand your idea :))

![Screenshot_20240604-210007](https://github.com/nevence/VacaYAY/assets/155846118/ef5425b0-8289-4bf0-920b-b6df72760027)

2024-06-06 12:45 UTC, pdavitkovic approved these changes

2024-06-06 12:45 UTC, merged