Feat/#5 create simple admin dashboard page
nevence/VacaYAY pull request #6
Opened 2024-06-12 21:29 UTC by nevence

added login, register, logout ui and functionalities, modelstate validation filter and exception handling filter

2024-06-12 21:36 UTC, nevence commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create simple admin dashboard page](https://trello.com/c/I52GPmv1/5-create-simple-admin-dashboard-page)

2024-06-13 06:05 UTC, pdavitkovic requested changes

2024-06-13 06:05 UTC, pdavitkovic commented on VacaYAY/BusinessLogicLayer/Dto/EmployeeDto/EmployeeForAuthenticationDto.cs
What about positional records?

2024-06-13 06:05 UTC, pdavitkovic commented on VacaYAY/BusinessLogicLayer/Extensions/EmployeeExtensions.cs
> +                Role = Enum.Parse<Roles>(oldEmployee.Login.Role),
I think this can be simplified: 

Enum.Value.ToString();

2024-06-13 06:05 UTC, pdavitkovic commented on VacaYAY/BusinessLogicLayer/Services/AuthService.cs
> +            var totalEmployees = await GetTotalEmployeesCountAsync();
Why not directly into properties?

2024-06-13 06:09 UTC, nevence commented on VacaYAY/BusinessLogicLayer/Dto/EmployeeDto/EmployeeForAuthenticationDto.cs
i'm not sure what you are referring to, could you please tell me more what you've meant?

2024-06-13 06:11 UTC, nevence commented on VacaYAY/BusinessLogicLayer/Extensions/EmployeeExtensions.cs
> +                Role = Enum.Parse<Roles>(oldEmployee.Login.Role),
i changed the property Role in EmployeeForRegistrationDto from string to Enum Roles, so this is actually parsing a string to enum (since OldEmployee has a property string Role)

2024-06-13 06:12 UTC, pdavitkovic commented on VacaYAY/BusinessLogicLayer/Dto/EmployeeDto/EmployeeForAuthenticationDto.cs
https://whitwu.com/want-to-make-your-c-dtos-more-manageable-turn-them-into-records

2024-06-17 08:45 UTC, pdavitkovic approved these changes

2024-06-17 08:45 UTC, merged